# Data types (This is called comments)
# String (Either inside " or ')
# Int (Whole numbers)
# Float (Decimal - 5.0, 9.9, 13.705)
# Boolean (True/False)

print("Hello World!")
print(5+8)
print(9*9)
print("Hello " * 5)
print("5 * 5")
print(10 / 2)
print(10 > 5)
print(10 < 5)